

services:

  mosquitto_broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
      - "8080:8080"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
    networks:
      - home_security_network


  python_collector:
    build: ./python_app
    container_name: python_collector
    depends_on:
      - mosquitto_broker
      - mysql_db
      - mongo_db
      - neo4j_db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: security_events
      MYSQL_HOST: mysql_db
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_HOST: mongo_db
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: neo4jpassword
      NEO4J_HOST: neo4j_db
    networks:
      - home_security_network


  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: security_events
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    networks:
      - home_security_network
    command: --default-authentication-plugin=mysql_native_password


  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - ./data/mongodb_data:/data/db
    networks:
      - home_security_network


  neo4j_db:
    image: neo4j:latest
    container_name: neo4j_db
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_bolt_listen_address: "0.0.0.0:7687"
      NEO4J_dbms_connector_http_listen_address: "0.0.0.0:7474"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j_data:/data
      - ./data/neo4j_plugins:/plugins
    networks:
      - home_security_network




  phpmyadmin_ui:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_ui
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306

    ports:
      - "8081:80"
    depends_on:
      - mysql_db
    networks:
      - home_security_network


  mongoexpress_ui:
    image: mongo-express:latest
    container_name: mongoexpress_ui
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopassword

    ports:
      - "8082:8081"
    depends_on:
      - mongo_db
    networks:
      - home_security_network


networks:
  home_security_network:
    driver: bridge