version: '3.8'

services:
  # 1. MQTT Broker
  mosquitto_broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  # 2. MySQL
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sensordb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 3. MongoDB
  mongo_db:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: home_sensor_data
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db


  # 4. Neo4j
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: "neo4j/strongpassword123"
      NEO4J_dbms_default__listen__address: 0.0.0.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  # 5. Subscriber
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscriber
    depends_on:
      - mosquitto_broker
      - mysql_db
      - mongo_db
      - neo4j
    environment:
      # MQTT
      MQTT_BROKER_HOST: mosquitto_broker
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC_ROOT: home
      # MySQL
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DB: sensordb
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      # MongoDB
      MONGO_HOST: mongo_db
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # Neo4j
      NEO4J_HOST: neo4j
      NEO4J_PORT: 7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: strongpassword123
    command: [ "python", "python_app/Subscriber.py" ]

  # 6. Publisher
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publisher
    depends_on:
      - mosquitto_broker
    environment:
      MQTT_BROKER_HOST: mosquitto_broker
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC_ROOT: home
    command: [ "python", "simulate_sensor.py" ]

  # 7. Mongo Express
  mongo_express:
    image: mongo-express:0.54.0
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo_db
    ports:
      - "8081:8081"
    environment:

      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
  # 8. phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: example
      PMA_ARBITRARY: 1

volumes:
  mosquitto_data:
  mosquitto_log:
  mysql_data:
  mongo_data:
  neo4j_data:
